export const Beauty_Makeup_Details = [
  {
    categoryName: "Beauty_Makeup",
    name: "NIVEA Soft Light Moisturizer for Face & Body",
    elobarateDescription:
      "Moisturizer for Face, Hand & Body, Instant Hydration",
    price: "0.001",
    rating : 9,
    ratingCount : 101,
    hint : "NIVEA_Soft_Light_Moisturizer",
    // images: [
    //   { url: "./NIVEA_Soft_Light_Moisturizer/image1" },
    //   { url: "./NIVEA_Soft_Light_Moisturizer/image2" },
    //   { url: "./NIVEA_Soft_Light_Moisturizer/image3" },
    //   { url: "./NIVEA_Soft_Light_Moisturizer/image4" },
    //   { url: "./NIVEA_Soft_Light_Moisturizer/image4" },
    // ],
    images: [
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image2.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image3.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4.jpg" },
    ],
    infoTable: {
      "Item Form": "Bar",
      "Skin Type": "Dry",
      Brand: "Dove",
      "Age Range (Description)": "Adult",
      "Number of Items": "1",
      "Net Quantity": "500.0 gram",
      Colour: "White",
      "Use for": "Face",
      "Product Benefits": "Moisturizing",
      "Recommended Uses For Product": "Smoothening,Moisturizing",
    },
    gender: "all",
    productId : '123',
    inStock : 20,
  },
  {
    categoryName: "Beauty_Makeup",
    name: "Garnier Men, Anti-Pimple Face Wash",
    elobarateDescription:
      "Repairs Skin & Balances Oils, AcnoFight, 100 g",
    price: 175,
    // images: [
    //   { url: "./Garnier_Men_Anti_Pimple_Face_Wash/image1" },
    //   { url: "./Garnier_Men_Anti_Pimple_Face_Wash/image1" },
    //   { url: "./Garnier_Men_Anti_Pimple_Face_Wash/image2" },
    //   { url: "./Garnier_Men_Anti_Pimple_Face_Wash/image3" },
    //   { url: "./Garnier_Men_Anti_Pimple_Face_Wash/image4" },
    // ],
    images: [
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image2" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image3" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4" },
    ],
    rating : 10,
    ratingCount : 121,
    hint : "Garnier_Men_Anti_Pimple_Face_Wash",
    infoTable: {
      "Item Form": "Paste",
      "Skin Type": "All",
      Brand: "Garnier",
      Scent: "Mint",
      "Age Range (Description)": "Adult",
      "Number of Items": "1",
      "Net Quantity": "100 gram",
      "Special Ingredients": "Anti Pimple",
      Colour: "Clear",
      "Item Package Quantity": "1",
    },
    gender: "men",
    productId : '321',
    inStock : 20,
  },
];
