export const categories = [
    { name : 'All Deals' , imageUrl : '/images/cat_images/All_Deals.svg'} ,
    { name : 'Trending Deals' , imageUrl : '/images/cat_images/Trending_Deals.svg'} , 
    { name : 'Welcome Offers' , imageUrl : '/images/cat_images/Welcome_Offers.svg'} , 
    { name : 'Mobiles' , imageUrl : '/images/cat_images/Mobiles.svg' } , 
    { name : 'Clothing' , imageUrl : '/images/cat_images/Clothing.svg'} , 
    { name : 'Footwear' , imageUrl : '/images/cat_images/Footwear.svg'} , 
    { name : 'Jewellery' , imageUrl : '/images/cat_images/Jewellery_Luggage_Watches.svg'} , 
    { name : 'Home' , imageUrl : '/images/cat_images/Home.svg'} , 
    { name : 'Kitchen' , imageUrl : '/images/cat_images/Kitchen.svg'} , 
    { name : 'Electronics' , imageUrl : '/images/cat_images/Electronics.svg'} , 
    { name : 'Furniture' , imageUrl : '/images/cat_images/Furniture.svg'} , 
    { name : 'Video Games' , imageUrl : '/images/cat_images/Video_Games_Software.svg'} , 
    { name : 'Grocery' , imageUrl : '/images/cat_images/Grocery.svg'} , 
    { name : 'Pet Supplies' , imageUrl : '/images/cat_images/Pet_Supplies.svg'} , 
    { name : 'Beauty & Makeup' , imageUrl : '/images/cat_images/Beauty_Makeup.svg'} , 
    { name : 'Kids and baby' , imageUrl : '/images/cat_images/Kids_baby.svg'} , 
    { name : 'Grooming & Wellness' , imageUrl : '/images/cat_images/Grooming_Wellness.svg'} , 
    { name : 'Sports & Fitness' , imageUrl : '/images/cat_images/Sports_Fitness.svg'} , 
    { name : 'Books & Stationery' , imageUrl : '/images/cat_images/Books_Stationery.svg'} , 
    { name : 'Health & Household' , imageUrl : '/images/cat_images/Health_Household.svg'} , 
    { name : 'Vehicle Accessories' , imageUrl : '/images/cat_images/Car_Motorbike_Accessories.svg'} , 
    { name : 'Musical Instruments' , imageUrl : '/images/cat_images/Musical_Instruments.svg'} , 
    { name : 'Smart accessories' , imageUrl : '/images/cat_images/Headphones_smartwatches_accessories.svg'} , 
    { name : 'TVs & appliances' , imageUrl : '/images/cat_images/TVs_appliances.svg'} , 
]

