export const Clothing = [
  {
    categoryName: "Clothing",
    name: "Alan Jones Clothing",
    elobarateDescription:
      "Alan Jones Clothing Colorblocked Boys Hoodies Sweatshirt",
    price: 600,
    rating: 9,
    ratingCount: 151,
    hint: "Alan_Jones_Clothing",
    // images: [
    //   { url: "./Alan_Jones_Clothing/image1" },
    //   { url: "./Alan_Jones_Clothing/image2" },
    //   { url: "./Alan_Jones_Clothing/image2" },
    //   { url: "./Alan_Jones_Clothing/image3" },
    //   { url: "./Alan_Jones_Clothing/image4" },
    // ],
    images: [
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image2.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image3.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4.jpg" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    infoTable: {
      "Material Composition": "60% Cotton, 40% Polyester",
      Style: "Casual",
      "Neck Style": "Hooded Neck",
      Pattern: "ColorBlock",
      "Package Dimensions": "31.9 x 25.4 x 5 cm; 320 Grams",
      "Date First Available": "25 June 2022",
      Manufacturer: "Alan Jones Clothing",
      ASIN: "B0B53HVQXC",
      "Item part number": "BOY22-SW103-RWB-6.7YRS",
      "Department ": "Boys",
      Manufacturer: "Alan Jones Clothing",
      "Item Weight": "320 g",
      "Generic Name": "Hooded Sweatshirt",
    },
    gender: "men",
    productId: "132",
    inStock : 20,
  },
  {
    categoryName: "Clothing",
    name: "Lymio Dresses for Women",
    elobarateDescription:
      "Lymio Dresses for Women White Color Women Dress (537)",
    price: 500,
    rating: 8,
    ratingCount: 81,
    hint: "Lymio_Dresses_for_Women",
    // images: [
    //   { url: "./Lymio_Dresses_for_Women/image1" },
    //   { url: "./Lymio_Dresses_for_Women/image2" },
    //   { url: "./Lymio_Dresses_for_Women/image2" },
    //   { url: "./Lymio_Dresses_for_Women/image3" },
    //   { url: "./Lymio_Dresses_for_Women/image4" },
    // ],
    images: [
      { url: "./Lymio_Dresses_for_Women/image1" },
      { url: "./Lymio_Dresses_for_Women/image2" },
      { url: "./Lymio_Dresses_for_Women/image2" },
      { url: "./Lymio_Dresses_for_Women/image3" },
      { url: "./Lymio_Dresses_for_Women/image4" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    infoTable: {
      Material: "CompositionComposition:100% Polyester",
      Style: "Dress",
      Pattern: "Floral",
      "Neck Style": "Square Neck",
      "Product Dimensions": "10 x 2 x 11 cm; 300 Grams",
      "Date First Available": "28 April 2022",
      Manufacturer: " J b Fashion",
      ASIN: "B09Z25L6XF",
      "Item model number": "D-537-XS",
      Department: "Women",
      Manufacturer: "J b Fashion, J b fashion_katargam",
      Packer: "J b fashion_katargam",
      "Item Weight": "300 g",
      "Item Dimensions LxWxH": "10 x 2 x 11 Centimeters",
      "Generic Name": "A-Line",
    },
    gender: "women",
    productId: "231",
    inStock : 20,
  },
];
