export const Footwear = [
  {
    categoryName: "Footwear",
    name: "crocs Unisex-Adult Sandals",
    elobarateDescription: "crocs Unisex-Adult Bayaband Clog Outdoor Sandals",
    price: 1747,
    rating: 9,
    ratingCount: 244,
    hint: "crocs_Unisex_Adult_Sandals",
    colors: ["Black/White", "Pepper/Navy", "Pepper/Navy"],
    images: [
      { url: "./Footwear/crocs_Unisex_Adult_Sandals/image1.jpg" },
      { url: "./Footwear/crocs_Unisex_Adult_Sandals/image1.jpg" },
      { url: "./Footwear/crocs_Unisex_Adult_Sandals/image2.jpg" },
      { url: "./Footwear/crocs_Unisex_Adult_Sandals/image2.jpg" },
      { url: "./Footwear/crocs_Unisex_Adult_Sandals/image2.jpg" },
    ],
    sizes: [
      "4 UK Men/ 5 UK Women",
      "5 UK Men/ 6 UK Women",
      "7 UK Men/ 8 UK Women",
      "8 UK Men/ 9 UK Women",
    ],
    infoTable: {
      "Closure Type": "Pull On",
      "Heel Type": "Flat",
      "Material Type": "Croslite",
      "Water Resistance Level": "Water Resistant",
      "Country of Origin": "USA",
    },
    gender: "all",
    productId: "456",
    inStock : 20
  },
  {
    categoryName: "Footwear",
    name: "Bacca Bucci Men's Walking Shoe",
    elobarateDescription: "Bacca Bucci Men's Walking Shoe",
    price: 500,
    rating: 10,
    ratingCount: 251,
    hint: "Bacca_Bucci_Mens_Walking_Shoe",
    colors: ["Blue", "Black"],
    colors: [
      { abbr: "Blue", hex: "#0000FF" },
      { abbr: "Black", hex: "#000000" },
    ],
    inStock : 20,
    // images: [
    //   { url: "./Footwear/Bacca_Bucci_Mens_Walking_Shoe/image1.jpg" },
    //   { url: "./Footwear/Bacca_Bucci_Mens_Walking_Shoe/image1.jpg" },
    //   { url: "./Footwear/Bacca_Bucci_Mens_Walking_Shoe/image2.jpg" },
    //   { url: "./Footwear/Bacca_Bucci_Mens_Walking_Shoe/image3.jpg" },
    //   { url: "./Footwear/Bacca_Bucci_Mens_Walking_Shoe/image4.jpg" },
    // ],
    images: [
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image2.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image3.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4.jpg" },
    ],
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK", "12 UK", "13 UK"],
    infoTable: {
      Material: " TypeMesh",
      "Closure Type": "Pull On",
      "Heel Type": "Flat",
      "Package Dimensions": "34 x 20.2 x 11.6 cm; 480 Grams",
      "Date First Available": "1 May 2019",
      Manufacturer: "Bacca Bucci Fashions Private Limited",
      ASIN: "B07R81T3V9",
      "Item part number": "BBMG8149B-06",
      Department: " mens",
      Manufacturer:
        "Bacca Bucci Fashions Private Limited",
      "Item Weight": " 480 g",
      "Generic Name ": "sports shoes",
    },
    gender: "men",
    productId: "654"
  },
];
