export const Mobiles = [
  {
    categoryName: "Mobiles",
    name: "Samsung Galaxy M13 5G",
    elobarateDescription:
      "Samsung Galaxy M13 5G (Stardust Brown, 4GB, 64GB Storage) | 5000mAh Battery | Upto 8GB RAM with RAM Plus",
    price: 16999,
    rating: 9,
    ratingCount: 263,
    hint: "samsung_galaxy_m13_5g",
    colors: [
      { abbr: "Midnight Blue", hex: "#191970" },
      { abbr: "Aqua Green", hex: "#00ffff" },
      { abbr: "Stardust Brown", hex: "#c8aa7f" },
      { abbr: "Brown", hex: "#964b00" },
      { abbr: "Dark Blue", hex: "#00008b" },
    ],
    // images: [
    //   { url: "./Mobiles/samsung_galaxy_m13_5g/Midnight_blue.jpg" },
    //   { url: "./Mobiles/samsung_galaxy_m13_5g/Aqua_Green.jpg" },
    //   { url: "./Mobiles/samsung_galaxy_m13_5g/Stardust_brown.jpg" },
    //   { url: "./Mobiles/samsung_galaxy_m13_5g/Brown.jpg" },
    //   { url: "./Mobiles/samsung_galaxy_m13_5g/Dark_blue.jpg" },
    // ],
    images: [
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image1.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image2.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image3.jpg" },
      { url: "/images/Products/Clothing/Alan_Jones_Clothing/image4.jpg" },
    ],
    infoTable: {
      OS: "Android 12.0",
      RAM: "4 GB",
      "Product Dimensions": "0.9 x 7.7 x 16.5 cm; 207 Grams",
      Batteries: "1 Lithium Ion batteries required. (included)",
      "Item model number": "SM-M135FDBPINS",
      "Connectivity technologies": "Bluetooth, Wi-Fi, USB",
      GPS: "GPS,Glonass,Beidou,Galileo",
      "Special features":
        "Auto Data Switching, Upto 12GB RAM with RAM Plus, Octa Core Processor, Fingerprint Sensor",
      "Colours displayed": "401 PPI with 16M Color",
      "Other display features": "Wireless",
      "Other camera features": "Front",
      "Audio Jack": "3.5 mm",
      Colour: "optional",
      "Battery Power Rating": "6000",
      "Whats in the box":
        "Handset,Sim Ejection Pin, User Guide,Adapter, Type A to C Cable",
      Manufacturer: "Samsung",
      "Country of Origin": "India",
      "Item Weight": "207 g",
    },
    gender: "all",
    productId: "465",
    inStock : 20,
  },
  {
    categoryName: "Mobiles",
    name: "OnePlus 10 Pro 5G",
    elobarateDescription: "OnePlus 10 Pro 5G (12GB RAM, 256GB Storage)",
    price: 66999,
    rating: 9,
    ratingCount: 51,
    hint: "one_plus_10_pro_5g",
    colors: [
      {
        color: "Volcanic Black",
        image: "./Mobiles/one_plus_10_pro_5g/Volcanic_Black.jpg",
      },
      {
        color: "Emerald Forest",
        image: "./Mobiles/one_plus_10_pro_5g/Emerald_Forest.jpg",
      },
    ],
    infoTable: {
      OS: "OxygenOS",
      RAM: "12 GB",
      "Product Dimensions": "7.4 x 0.9 x 16.3 cm; 200 Grams",
      Batteries: "1 Lithium Polymer batteries required. (included)",
      "Wireless communication technologies": "Cellular",
      "Connectivity technologies": "USB",
      "Special features": "Fingerprint Scanner, USB, LED Flash, Camera",
      "Display technology": "AMOLED",
      "Other display features": "Wireless",
      "Other camera features": "Front",
      Colour: "Emerald Fo:rest",
      "Battery Power Rating": "5000",
      "Whats in the box": "SIM Tray Ejector, Adapter, Phone Case, USB Cable",
      Manufacturer: "Oppo Mobiles India Private Limited",
      "Country of Origin": "India",
      "Item Weight": "200 g",
    },
    gender: "all",
    productId: "564",
    inStock : 20,
  },
];
